import type { Restaurant } from "../model/Restaurant";

export const INITIAL_RESTAURANTS: Restaurant[] = [
  { id: "1", name: "Le Jardin Céleste", address: "42 Rue de Rivoli, Paris 75001", contact: "+33 1 42 60 81 00", description: "An elevated French brasserie celebrating seasonal produce from the Loire Valley. Our chef brings 20 years of Michelin-starred experience crafting each dish as an edible work of art.", cuisine: "French", rating: 4.9, tables: 24, status: "active", createdAt: new Date("2021-03-15") },
  { id: "2", name: "Osaka no Yume", address: "8 Takashimaya St, Tokyo 160-0022", contact: "+81 3 5362 7000", description: "A kaiseki journey through Japan's culinary seasons. Each 12-course omakase tells the story of a single ingredient, elevated through centuries of Japanese technique.", cuisine: "Japanese", rating: 4.8, tables: 16, status: "active", createdAt: new Date("2020-11-20") },
  { id: "3", name: "Fuoco e Sale", address: "Piazza Navona 15, Rome 00186", contact: "+39 06 6880 1094", description: "Authentic Roman trattoria where Nonna's recipes meet contemporary refinement. Wood-fired ovens imported from Naples give our Neapolitan pizzas an irreplaceable char.", cuisine: "Italian", rating: 4.7, tables: 30, status: "active", createdAt: new Date("2019-06-08") },
  { id: "4", name: "Saffron & Smoke", address: "12 Corniche Road, Dubai Marina", contact: "+971 4 399 9999", description: "A modern Persian gastronomic experience where ancient spice routes meet contemporary plating. Fragrant slow-braised lamb and rose-water desserts define our signature menu.", cuisine: "Persian", rating: 4.6, tables: 40, status: "active", createdAt: new Date("2022-01-10") },
  { id: "5", name: "The Copper Kettle", address: "7 Charlotte Square, Edinburgh EH2 4DR", contact: "+44 131 225 5109", description: "A Victorian townhouse transformed into Edinburgh's most intimate dining room. Scottish game, wild sea fish, and highland whisky form the pillars of our tasting menu.", cuisine: "Scottish", rating: 4.8, tables: 18, status: "active", createdAt: new Date("2018-09-22") },
  { id: "6", name: "Casa de los Sueños", address: "Calle Gran Vía 28, Madrid 28013", contact: "+34 91 532 8745", description: "Innovative nuevo cocina celebrating Spain's rich agricultural tradition. Our vermouth bar and tapas experience precede a five-course journey through Iberian terroir.", cuisine: "Spanish", rating: 4.5, tables: 35, status: "inactive", createdAt: new Date("2021-07-14") },
  { id: "7", name: "Lotus & Lemongrass", address: "35 Sukhumvit Soi 11, Bangkok 10110", contact: "+66 2 252 7998", description: "Modern Thai cuisine that honours the complexity of regional recipes seldom seen outside local homes. Botanical cocktails crafted with Thai herbs complete the aromatic journey.", cuisine: "Thai", rating: 4.7, tables: 28, status: "active", createdAt: new Date("2020-04-18") },
  { id: "8", name: "Brisket & Barrel", address: "1540 N Damen Ave, Chicago IL 60622", contact: "+1 773 384 7275", description: "A hymn to American smoke culture — 18-hour briskets, heritage pork ribs, and handcrafted bourbon barrels age quietly in our cellar. Nashville influence, Chicago soul.", cuisine: "American BBQ", rating: 4.6, tables: 45, status: "active", createdAt: new Date("2019-12-01") },
  { id: "9", name: "Alma do Mar", address: "Doca de Alcântara Norte, Lisbon 1350-352", contact: "+351 21 362 0203", description: "Perched over the Tagus, our kitchen celebrates Portugal's deep seafaring heritage. Freshly landed Atlantic catch arrives each morning to be transformed by wood-coal fire.", cuisine: "Portuguese", rating: 4.9, tables: 20, status: "active", createdAt: new Date("2023-02-28") },
  { id: "10", name: "Bergwald Stube", address: "Maximilianstr. 17, Munich 80539", contact: "+49 89 212 23970", description: "Alpine Bavarian tradition elevated for the discerning palate. Hand-rolled pasta, venison carpaccio, and biodynamic wines from Austria and South Tyrol anchor our seasonal menu.", cuisine: "Bavarian", rating: 4.4, tables: 22, status: "active", createdAt: new Date("2021-11-05") },
  { id: "11", name: "Terroir & Tide", address: "123 Harbour St, Sydney NSW 2000", contact: "+61 2 9241 1111", description: "A celebration of Australian coastal abundance. Indigenous ingredients — finger lime, saltbush, lemon myrtle — weave through a menu shaped by Polynesian and Asian currents.", cuisine: "Australian", rating: 4.7, tables: 32, status: "active", createdAt: new Date("2022-08-15") },
  { id: "12", name: "Tigre & Ceviche", address: "Calle Berlín 701, Miraflores, Lima", contact: "+51 1 651 1000", description: "Lima's celebrated Nikkei tradition lives here — the sublime marriage of Peruvian ceviche craft and Japanese precision. Tiger's milk cocktails are legendary among locals.", cuisine: "Peruvian", rating: 4.8, tables: 26, status: "active", createdAt: new Date("2020-03-12") },
];